"""
Export service for generating Word and PDF documents.
"""
from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from io import BytesIO
from datetime import datetime
from typing import Optional


class ExportService:
    """Service for exporting transcriptions and summaries to various formats."""

    @staticmethod
    def create_docx(
        transcription_text: str,
        summary_text: Optional[str] = None,
        recording_filename: str = "recording",
        created_at: Optional[datetime] = None
    ) -> BytesIO:
        """
        Create a Word document with transcription and optional summary.

        Args:
            transcription_text: The transcription text
            summary_text: Optional summary text
            recording_filename: Name of the recording
            created_at: Recording creation date

        Returns:
            BytesIO buffer containing the Word document
        """
        document = Document()

        # Add title
        title = document.add_heading('Take My Dictation', level=0)
        title.alignment = WD_ALIGN_PARAGRAPH.CENTER

        # Add recording info
        info = document.add_paragraph()
        info.add_run(f'Recording: {recording_filename}\n').bold = True
        if created_at:
            info.add_run(f'Date: {created_at.strftime("%B %d, %Y at %I:%M %p")}\n')
        info.alignment = WD_ALIGN_PARAGRAPH.CENTER

        document.add_paragraph()  # Spacing

        # Add transcription section
        document.add_heading('Full Transcription', level=1)
        transcription_para = document.add_paragraph(transcription_text)
        transcription_para.alignment = WD_ALIGN_PARAGRAPH.LEFT

        # Add summary section if provided
        if summary_text:
            document.add_page_break()
            document.add_heading('AI-Generated Summary', level=1)
            summary_para = document.add_paragraph(summary_text)
            summary_para.alignment = WD_ALIGN_PARAGRAPH.LEFT

        # Add footer
        document.add_paragraph()
        footer = document.add_paragraph()
        footer.add_run(f'\nGenerated by Take My Dictation - {datetime.now().strftime("%B %d, %Y")}')
        footer.alignment = WD_ALIGN_PARAGRAPH.CENTER
        footer_run = footer.runs[0]
        footer_run.font.size = Pt(9)
        footer_run.font.color.rgb = RGBColor(128, 128, 128)

        # Save to BytesIO
        buffer = BytesIO()
        document.save(buffer)
        buffer.seek(0)
        return buffer

    @staticmethod
    def create_pdf(
        transcription_text: str,
        summary_text: Optional[str] = None,
        recording_filename: str = "recording",
        created_at: Optional[datetime] = None
    ) -> BytesIO:
        """
        Create a PDF document with transcription and optional summary.

        Args:
            transcription_text: The transcription text
            summary_text: Optional summary text
            recording_filename: Name of the recording
            created_at: Recording creation date

        Returns:
            BytesIO buffer containing the PDF document
        """
        buffer = BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=letter, topMargin=0.75*inch, bottomMargin=0.75*inch)

        # Container for the 'Flowable' objects
        elements = []

        # Define styles
        styles = getSampleStyleSheet()

        # Title style
        title_style = ParagraphStyle(
            'CustomTitle',
            parent=styles['Heading1'],
            fontSize=24,
            textColor=RGBColor(0x4F, 0x46, 0xE5),  # Primary color
            spaceAfter=12,
            alignment=TA_CENTER,
            fontName='Helvetica-Bold'
        )

        # Info style
        info_style = ParagraphStyle(
            'Info',
            parent=styles['Normal'],
            fontSize=11,
            alignment=TA_CENTER,
            spaceAfter=20
        )

        # Heading style
        heading_style = ParagraphStyle(
            'CustomHeading',
            parent=styles['Heading2'],
            fontSize=16,
            textColor=RGBColor(0x1F, 0x29, 0x37),  # Dark gray color
            spaceAfter=12,
            spaceBefore=12
        )

        # Body style
        body_style = ParagraphStyle(
            'CustomBody',
            parent=styles['Normal'],
            fontSize=11,
            leading=16,
            alignment=TA_LEFT,
            spaceAfter=12
        )

        # Footer style
        footer_style = ParagraphStyle(
            'Footer',
            parent=styles['Normal'],
            fontSize=9,
            textColor=RGBColor(128, 128, 128),
            alignment=TA_CENTER,
            spaceBefore=20
        )

        # Add title
        elements.append(Paragraph('Take My Dictation', title_style))
        elements.append(Spacer(1, 0.2*inch))

        # Add recording info
        info_text = f'<b>Recording:</b> {recording_filename}'
        if created_at:
            info_text += f'<br/><b>Date:</b> {created_at.strftime("%B %d, %Y at %I:%M %p")}'
        elements.append(Paragraph(info_text, info_style))
        elements.append(Spacer(1, 0.3*inch))

        # Add transcription
        elements.append(Paragraph('Full Transcription', heading_style))
        # Split transcription into paragraphs
        for para in transcription_text.split('\n\n'):
            if para.strip():
                elements.append(Paragraph(para.replace('\n', '<br/>'), body_style))

        # Add summary if provided
        if summary_text:
            elements.append(PageBreak())
            elements.append(Paragraph('AI-Generated Summary', heading_style))
            # Split summary into paragraphs
            for para in summary_text.split('\n\n'):
                if para.strip():
                    elements.append(Paragraph(para.replace('\n', '<br/>'), body_style))

        # Add footer
        elements.append(Spacer(1, 0.5*inch))
        footer_text = f'Generated by Take My Dictation - {datetime.now().strftime("%B %d, %Y")}'
        elements.append(Paragraph(footer_text, footer_style))

        # Build PDF
        doc.build(elements)
        buffer.seek(0)
        return buffer


# Create a global instance
export_service = ExportService()
